# Generated by Django 4.2.2 on 2023-06-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='thoughts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pers_name', models.CharField(max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
    ]
